packages:
  - apps/*
  - packages/*

overrides:
  zod: 4.4.3

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  cpu-features: false
  esbuild: set this to true or false

minimumReleaseAgeExclude:
  - '@agentclientprotocol/claude-agent-acp@0.55.0'
