import { execFile as execFileCb } from "node:child_process"
import { existsSync } from "node:fs"
import { mkdir, readFile, rm, writeFile } from "node:fs/promises"
import { homedir, userInfo } from "node:os"
import { dirname, join } from "node:path"
import { promisify } from "node:util"

import { spawnInteractive } from "../installers.js"
import { buildServicePath } from "./env.js"
import { resolveGenticExecutable } from "./entry.js"
import type {
  ExecFn,
  ServiceBackend,
  ServiceInstallOptions,
  ServiceLogsOptions,
  ServiceScope,
  ServiceStatus,
} from "./types.js"

const execFileAsync = promisify(execFileCb)

const defaultExec: ExecFn = (file, args, options) =>
  execFileAsync(file, args, { ...options, encoding: "utf8" })

const SERVICE_NAME = "gentic.service"
const SYSTEM_UNIT_PATH = "/etc/systemd/system/gentic.service"

// Disabling the unit is how `stop()` keeps a stopped worker stopped across a
// reboot, but it also erases systemd's record of whether the user ever asked
// for boot start. Stamp that choice into the unit file so `start()` can put it
// back without second-guessing an explicit `--no-boot`.
const BOOT_MARKER = "# gentic-enable-on-boot="
const BOOT_DISABLED_MARKER = new RegExp(`^${BOOT_MARKER}false\\s*$`, "m")

function describe(error: unknown): string {
  if (error && typeof error === "object" && "stderr" in error) {
    const stderr = (error as { stderr?: string }).stderr
    if (stderr && stderr.trim().length > 0) return stderr.trim()
  }
  return error instanceof Error ? error.message : String(error)
}

function quoteSystemdEnv(name: string, value: string): string {
  return `"${name}=${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
}

export class SystemdBackend implements ServiceBackend {
  readonly name = "systemd"

  constructor(
    private readonly scope: ServiceScope = "user",
    private readonly exec: ExecFn = defaultExec,
  ) {}

  private unitPath(): string {
    return this.scope === "system"
      ? SYSTEM_UNIT_PATH
      : join(homedir(), ".config", "systemd", "user", SERVICE_NAME)
  }

  private scopeArgs(): string[] {
    return this.scope === "system" ? [] : ["--user"]
  }

  // `systemctl --user` locates the per-user bus via XDG_RUNTIME_DIR
  // (/run/user/<uid>/bus). That variable is often absent in SSH and other
  // non-login shells, which makes systemctl fail with "Failed to connect to
  // bus: No medium found". Default it to the standard runtime dir when the
  // directory exists so user-scoped commands work without a login session.
  private userRuntimeDir(): string | undefined {
    if (process.env.XDG_RUNTIME_DIR) return process.env.XDG_RUNTIME_DIR
    const runtimeDir = `/run/user/${userInfo().uid}`
    return existsSync(runtimeDir) ? runtimeDir : undefined
  }

  private execEnv(): NodeJS.ProcessEnv {
    if (this.scope === "system") return process.env
    const runtimeDir = this.userRuntimeDir()
    if (!runtimeDir || runtimeDir === process.env.XDG_RUNTIME_DIR) return process.env
    return { ...process.env, XDG_RUNTIME_DIR: runtimeDir }
  }

  private async systemctl(...args: string[]): Promise<{ stdout: string; stderr: string }> {
    try {
      return await this.exec("systemctl", [...this.scopeArgs(), ...args], { env: this.execEnv() })
    } catch (error) {
      throw new Error(`systemctl ${args.join(" ")} failed: ${describe(error)}`)
    }
  }

  isAvailable(): boolean {
    if (!existsSync("/run/systemd/system")) return false
    // A user-scoped install is useless without a reachable per-user bus.
    if (this.scope === "user" && !this.userRuntimeDir()) return false
    return true
  }

  private unitFileContents(enableOnBoot: boolean): string {
    const { command, args } = resolveGenticExecutable()
    const execStart = [command, ...args, "run"].map((arg) => `"${arg.replaceAll('"', '\\"')}"`).join(" ")
    const servicePath = buildServicePath()
    return `# Managed by gentic — regenerated by \`gentic start\`.
${BOOT_MARKER}${enableOnBoot}
[Unit]
Description=Gentic agent worker
After=network-online.target

[Service]
ExecStart=${execStart}
Restart=on-failure
RestartSec=5
Environment=${quoteSystemdEnv("NODE_ENV", "production")} ${quoteSystemdEnv("PATH", servicePath)}

[Install]
WantedBy=default.target
`
  }

  // Whether `gentic start` was last run without `--no-boot`. Units written
  // before this marker existed predate `--no-boot` surviving a stop, and the
  // default has always been to start on boot.
  private async wantsBootStart(): Promise<boolean> {
    try {
      return !BOOT_DISABLED_MARKER.test(await readFile(this.unitPath(), "utf8"))
    } catch {
      return true
    }
  }

  private async enableBootStart(): Promise<void> {
    await this.systemctl("enable", SERVICE_NAME)
    if (this.scope === "system") return

    const user = userInfo().username
    try {
      await this.exec("loginctl", ["enable-linger", user])
    } catch (error) {
      throw new Error(
        `Enabled gentic.service but failed to enable lingering for user "${user}" ` +
          `(${describe(error)}). Without lingering, the user service will not start ` +
          "until you log in again after a reboot. Run `loginctl enable-linger " +
          `${user}\` manually with sufficient privileges, or use \`gentic start --system\` ` +
          "to install a system-level unit instead.",
      )
    }
  }

  // Undo the disable that `stop()` recorded, unless the install asked for
  // `--no-boot`. Cheap to skip when systemd already agrees.
  private async restoreBootStart(): Promise<void> {
    // Leave a missing unit to systemctl, whose "unit not found" beats an
    // `enable` failure at explaining what went wrong.
    if (!existsSync(this.unitPath())) return
    if (!(await this.wantsBootStart())) return
    if (await this.isEnabledOnBoot()) return
    await this.enableBootStart()
  }

  async install(opts: ServiceInstallOptions): Promise<void> {
    const unitPath = this.unitPath()
    await mkdir(dirname(unitPath), { recursive: true })
    await writeFile(unitPath, this.unitFileContents(opts.enableOnBoot), "utf8")
    await this.systemctl("daemon-reload")

    if (opts.enableOnBoot) {
      await this.enableBootStart()
      return
    }

    // Reinstalling with `--no-boot` has to clear an enable left by an earlier
    // boot-enabled install, or `gentic status` would report Boot: enabled.
    await this.systemctl("disable", SERVICE_NAME)
  }

  async uninstall(): Promise<void> {
    const unitPath = this.unitPath()
    if (!existsSync(unitPath)) return

    await this.systemctl("stop", SERVICE_NAME).catch(() => undefined)
    await this.systemctl("disable", SERVICE_NAME).catch(() => undefined)
    await rm(unitPath, { force: true })
    await this.systemctl("daemon-reload")
  }

  async start(): Promise<void> {
    await this.restoreBootStart()
    await this.systemctl("start", SERVICE_NAME)
  }

  async stop(): Promise<void> {
    await this.systemctl("stop", SERVICE_NAME)
    // `systemctl stop` lasts only for this boot — the unit is still wanted by
    // default.target, so the worker would come back at the next login or
    // reboot. Disabling it is what makes the stop stick.
    await this.systemctl("disable", SERVICE_NAME)
  }

  async restart(): Promise<void> {
    await this.restoreBootStart()
    await this.systemctl("restart", SERVICE_NAME)
  }

  async reload(): Promise<void> {
    await this.systemctl("kill", "--signal=HUP", "--kill-who=main", SERVICE_NAME)
  }

  async status(): Promise<ServiceStatus> {
    if (!existsSync(this.unitPath())) {
      return { state: "not-installed" }
    }

    const { stdout } = await this.systemctl(
      "show",
      SERVICE_NAME,
      "--property=ActiveState",
      "--property=MainPID",
      "--property=ActiveEnterTimestamp",
    )

    const props = Object.fromEntries(
      stdout
        .split("\n")
        .filter((line) => line.includes("="))
        .map((line) => {
          const index = line.indexOf("=")
          return [line.slice(0, index), line.slice(index + 1)]
        }),
    )

    const running = props.ActiveState === "active"
    const pid = Number(props.MainPID)
    const since = props.ActiveEnterTimestamp ? new Date(props.ActiveEnterTimestamp) : undefined

    return {
      state: running ? "running" : "stopped",
      pid: running && pid > 0 ? pid : undefined,
      since: running && since && !Number.isNaN(since.getTime()) ? since : undefined,
    }
  }

  async isEnabledOnBoot(): Promise<boolean> {
    if (!existsSync(this.unitPath())) return false

    const enabled = await this.systemctl("is-enabled", SERVICE_NAME)
      .then(({ stdout }) => stdout.trim() === "enabled")
      .catch(() => false)
    if (!enabled) return false
    if (this.scope === "system") return true

    const user = userInfo().username
    try {
      const { stdout } = await this.exec("loginctl", ["show-user", user, "--property=Linger"])
      return stdout.trim() === "Linger=yes"
    } catch {
      return false
    }
  }

  async logs(opts: ServiceLogsOptions): Promise<void> {
    const args = [...this.scopeArgs(), "-u", SERVICE_NAME]
    args.push(opts.follow ? "-f" : "--no-pager")

    await spawnInteractive("journalctl", args)
  }
}
