import {
  IconAlertCircle,
  IconAlertOctagon,
  IconAlertTriangle,
  IconCircleCheck,
  IconCircleDashed,
  IconCircleX,
  IconClock,
  IconDownload,
  IconEye,
  IconFlask,
  IconGitMerge,
  IconMessage2,
  IconMessageQuestion,
  IconPencil,
  IconPlayerPause,
  IconRocket,
  IconShieldCheck,
  IconThumbUp,
} from "@tabler/icons-react"

import type { IssueStatus } from "@gentic/validators/issues"

// Shared with the status dropdown (`issue-detail-view.tsx`) so status
// milestones elsewhere (e.g. the timeline) stay visually consistent.
export const statusLabels: Record<IssueStatus, string> = {
  draft: "Draft",
  todo: "To do",
  queued: "Queued",
  held: "On hold",
  "in-progress": "In progress",
  "waiting-for-input": "Waiting for input",
  testing: "Testing",
  "tests-failed": "Tests failed",
  "ready-for-review": "Ready for review",
  "changes-requested": "Changes requested",
  approved: "Approved",
  merged: "Merged",
  deploying: "Deploying",
  "deploy-failed": "Deploy failed",
  validating: "Validating",
  "run-failed": "Run failed",
  completed: "Completed",
  cancelled: "Cancelled",
}

export const statusStyles: Record<IssueStatus, string> = {
  draft: "bg-muted text-muted-foreground",
  todo: "bg-muted text-muted-foreground",
  queued: "bg-muted text-muted-foreground",
  held: "bg-muted text-muted-foreground",
  "in-progress": "bg-muted text-muted-foreground",
  "waiting-for-input": "bg-muted text-muted-foreground",
  testing: "bg-muted text-muted-foreground",
  "tests-failed": "bg-muted text-muted-foreground",
  "ready-for-review": "bg-muted text-muted-foreground",
  "changes-requested": "bg-muted text-muted-foreground",
  approved: "bg-muted text-muted-foreground",
  merged: "bg-muted text-muted-foreground",
  deploying: "bg-muted text-muted-foreground",
  "deploy-failed": "bg-muted text-muted-foreground",
  validating: "bg-muted text-muted-foreground",
  "run-failed": "bg-muted text-muted-foreground",
  completed: "bg-muted text-muted-foreground",
  cancelled: "bg-muted text-muted-foreground",
}

export const statusIconStyles: Record<IssueStatus, string> = {
  draft: "text-muted-foreground",
  todo: "text-muted-foreground",
  queued: "text-primary",
  held: "text-amber-600 dark:text-amber-300",
  "in-progress": "text-blue-600 dark:text-blue-300",
  "waiting-for-input": "text-amber-600 dark:text-amber-300",
  testing: "text-sky-600 dark:text-sky-300",
  "tests-failed": "text-red-600 dark:text-red-300",
  "ready-for-review": "text-violet-600 dark:text-violet-300",
  "changes-requested": "text-orange-600 dark:text-orange-300",
  approved: "text-teal-600 dark:text-teal-300",
  merged: "text-indigo-600 dark:text-indigo-300",
  deploying: "text-blue-600 dark:text-blue-300",
  "deploy-failed": "text-rose-600 dark:text-rose-300",
  validating: "text-cyan-600 dark:text-cyan-300",
  "run-failed": "text-destructive",
  completed: "text-emerald-600 dark:text-emerald-300",
  cancelled: "text-muted-foreground",
}

export const statusIcons: Record<IssueStatus, typeof IconClock> = {
  draft: IconPencil,
  todo: IconCircleDashed,
  queued: IconDownload,
  held: IconPlayerPause,
  "in-progress": IconClock,
  "waiting-for-input": IconMessageQuestion,
  testing: IconFlask,
  "tests-failed": IconAlertTriangle,
  "ready-for-review": IconEye,
  "changes-requested": IconMessage2,
  approved: IconThumbUp,
  merged: IconGitMerge,
  deploying: IconRocket,
  "deploy-failed": IconAlertOctagon,
  validating: IconShieldCheck,
  "run-failed": IconAlertCircle,
  completed: IconCircleCheck,
  cancelled: IconCircleX,
}
