alter table public.issues
  add column active_run_id uuid;

alter table public.messages
  add column seq bigint generated by default as identity,
  add column consumed_by_run_id uuid,
  add column consumed_at timestamptz;

with numbered as (
  select
    id,
    row_number() over (order by created_at, id) as seq
  from public.messages
)
update public.messages
set seq = numbered.seq
from numbered
where messages.id = numbered.id;

alter table public.messages
  alter column seq set not null,
  add constraint messages_consumed_by_run_requires_consumed_at check (
    (consumed_by_run_id is null and consumed_at is null)
    or (consumed_by_run_id is not null and consumed_at is not null)
  );

select setval(
  pg_get_serial_sequence('public.messages', 'seq'),
  coalesce((select max(seq) from public.messages), 1)
);

create unique index messages_seq_key on public.messages(seq);
create index messages_issue_user_unconsumed_seq_idx
  on public.messages(issue_id, seq)
  where role = 'user' and consumed_by_run_id is null;
create index messages_consumed_by_run_id_idx
  on public.messages(consumed_by_run_id)
  where consumed_by_run_id is not null;

revoke update on public.messages from authenticated;
drop policy if exists "Users can update messages for their own issues"
  on public.messages;

create or replace function public.start_issue_from_draft(p_issue_id uuid)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_prompt text;
begin
  update public.issues
  set
    status = 'todo',
    usage_limit_reset_at = null,
    updated_at = now()
  where id = p_issue_id
    and status = 'draft'
  returning prompt into v_prompt;

  if not found then
    raise exception 'Issue is not a draft or was not found'
      using errcode = 'P0002';
  end if;

  insert into public.messages(issue_id, role, content)
  values (p_issue_id, 'user', coalesce(v_prompt, ''));
end;
$$;

create or replace function public.reset_issue_run(
  p_issue_id uuid,
  p_agent_provider text
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_prompt text;
begin
  if p_agent_provider not in ('claude_code', 'codex') then
    raise exception 'Invalid agent provider'
      using errcode = '22023';
  end if;

  select prompt into v_prompt
  from public.issues
  where id = p_issue_id;

  if not found then
    raise exception 'Issue not found'
      using errcode = 'P0002';
  end if;

  delete from public.messages
  where issue_id = p_issue_id;

  delete from public.issue_pull_requests
  where issue_id = p_issue_id;

  update public.issues
  set
    status = 'todo',
    agent_provider = p_agent_provider,
    session_id = null,
    active_run_id = null,
    run_error = null,
    run_started_at = null,
    run_finished_at = null,
    usage_limit_reset_at = null,
    pr_url = null,
    updated_at = now()
  where id = p_issue_id;

  insert into public.messages(issue_id, role, content)
  values (p_issue_id, 'user', coalesce(v_prompt, ''));
end;
$$;

create or replace function public.send_issue_user_message(
  p_issue_id uuid,
  p_content text
)
returns table(id uuid, created_at timestamptz)
language plpgsql
security invoker
set search_path = public
as $$
begin
  return query
  with inserted as (
    insert into public.messages(issue_id, role, content)
    values (p_issue_id, 'user', p_content)
    returning messages.id, messages.created_at
  ),
  requeued as (
    update public.issues
    set
      status = 'todo',
      usage_limit_reset_at = null,
      updated_at = now()
    where issues.id = p_issue_id
      and issues.status not in ('draft', 'todo', 'queued', 'held', 'in-progress')
    returning issues.id
  )
  select inserted.id, inserted.created_at
  from inserted;
end;
$$;

create or replace function public.finish_issue_run_if_no_pending(
  p_issue_id uuid,
  p_run_id uuid,
  p_status text,
  p_run_finished_at timestamptz,
  p_pr_url text default null
)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
begin
  if p_status not in ('ready-for-review', 'waiting-for-input') then
    raise exception 'Invalid terminal run status'
      using errcode = '22023';
  end if;

  update public.issues
  set
    status = p_status,
    run_finished_at = p_run_finished_at,
    pr_url = coalesce(p_pr_url, pr_url),
    active_run_id = null,
    updated_at = now()
  where id = p_issue_id
    and active_run_id = p_run_id
    and not exists (
      select 1
      from public.messages
      where messages.issue_id = p_issue_id
        and messages.role = 'user'
        and messages.consumed_by_run_id is null
    );

  return found;
end;
$$;

revoke all on function public.start_issue_from_draft(uuid) from public;
revoke all on function public.reset_issue_run(uuid, text) from public;
revoke all on function public.send_issue_user_message(uuid, text) from public;
revoke all on function public.finish_issue_run_if_no_pending(
  uuid,
  uuid,
  text,
  timestamptz,
  text
) from public;

grant execute on function public.start_issue_from_draft(uuid) to authenticated;
grant execute on function public.start_issue_from_draft(uuid) to service_role;
grant execute on function public.reset_issue_run(uuid, text) to authenticated;
grant execute on function public.reset_issue_run(uuid, text) to service_role;
grant execute on function public.send_issue_user_message(uuid, text)
  to authenticated;
grant execute on function public.send_issue_user_message(uuid, text)
  to service_role;
grant execute on function public.finish_issue_run_if_no_pending(
  uuid,
  uuid,
  text,
  timestamptz,
  text
) to service_role;
